sudo: false
language: java
cache:
  directories:
notifications:
  email: false
before_install:
  - pip install --user codecov
before_script:
  - cd java2word
script:
  - mvn clean install
  - ant findbugs
  - ant pmd
  - ant cpd
  - ant cobertura
  - ant javancss
  - ant checkstyle
after_success:
  - codecov
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
